<?php include'header.php';?>

      <!-- content-1 -->
      <section class="content-1">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1">
            	<center><h3>Syncify Terms of Agreement</h3></center>

            	<p>THE LEGAL AGREEMENTS SET OUT BELOW GOVERN YOUR USE OF THE SYNCIFY APP. TO AGREE TO THESE TERMS, CLICK "AGREE." IF YOU DO NOT AGREE TO THESE TERMS, DO NOT CLICK "AGREE," AND DO NOT USE THE SERVICES.
	            	
	            	<ol>
		            	<li><strong>Introduction</strong><br>
Thanks for choosing Syncify (“Syncify”, “we”, “us”, “our”). By using the Syncify service, websites, or software applications (together, the “Syncify Service” or “Service you are entering into a binding contract with our company. Your agreement with us includes these Terms and Conditions of Use (“Terms”) and our Privacy Policy. If you don’t agree with these Terms, then please don’t use the Service. We’re pleased to make our Service available to you. The Syncify Service includes social and interactive features.
In order to use the Syncify Service, you need to (a) be of the age of majority in your province or territory of residence, or be 13 or older and have your parent or guardian’s consent to these Terms, (b) have the power to enter a binding contract with us and are not barred from doing so under any applicable laws, and (c) be resident in the Local Country. You also warrant that any registration information that you submit to Syncify is true, accurate and complete, and you agree to keep it that way at all times.
</li>
		            	<li><strong>Changes to the Agreements</strong><br>
Occasionally we may, in our discretion, make changes to the Syncify Service and Agreements. If we make changes, which we believe are material, we will provide you with prominent notice as appropriate under the circumstances, e.g. by email or by prominent information within the Service. By continuing to use the Service after those changes are made, you are expressing and acknowledging your acceptance of the changes.
</li>
		            	<li><strong>Enjoying Syncify</strong><br>
Syncify provides you access to digital music and other content (“Apple Music Products" & “Spotify” etc.) for end user use only under the terms and conditions set forth in this Agreement. Syncify account holders may access the Syncify Service by our Free Service: an ad-based, free-of-charge service.
Use of the Syncify’s Service requires a compatible device, Internet access, and certain software; may require periodic updates; and may be affected by the performance of these factors. High-speed Internet access is strongly recommended for regular use and access; cellular data fees may apply. 
</li>
		            	<li><strong>Licence and assignment</strong><br>
The Syncify Service and the content provided through it are the property of Syncify or Syncify’s licensors, and we grant you a limited, non-exclusive, revocable licence to make personal, non-commercial (except as permitted under Section Brand Accounts) use of the Syncify Service and to receive the media content made available through the Syncify Service in your Local Country, based on the Subscription or Trial, you have selected (the “Licence”). This Licence shall remain in effect for a period of 20 years unless terminated by you or Syncify.
The Syncify software applications are licensed, not sold, to you, and Syncify retains ownership of all copies of the Syncify software applications even after installation on your Devices. Syncify may assign these Agreements or any part of them without restrictions. You may not assign these Agreements or any part of them, nor transfer or sub-licence your rights under this Licence, to any third party.
All Syncify trademarks, service marks, trade names, logos, domain names, and any other features of the Syncify brand are the sole property of Syncify. This Licence does not grant you any rights to use the Syncify trademarks, service marks, trade names, logos, domain names, or any other features of the Syncify brand, whether for commercial or non-commercial use.
You agree to abide by our User Guidelines and not to use the Syncify Service (including but not limited to its content) in any manner not expressly permitted by the Terms.
Third party software libraries included in the Syncify Service are licensed to you either under these Terms, or under the relevant third party software library’s licence terms as published in the help or settings section of our desktop and mobile client and on our website.
</li>
		            	<li><strong>Third Party Applications</strong><br>
The Syncify Service provides a platform for third party applications, websites and services to make available products and services to you (“Third Party Applications”), and your use of these Third Party Applications is subject to their terms of use. You understand and agree that Syncify is not responsible or liable for the behavior, features, or content of any Third Party Application. 
</li>
		            	<li><strong>User generated content</strong><br>
Syncify users may post, upload and/or contribute (“post”) content to the Service, including pictures, text and playlist compilations (“User Content”). You are solely responsible for any User Content you provide and for any consequences thereof. You represent that you have the right to post any User Content which you post to the Service, and that such User Content, or its use by us as contemplated by this Agreement, does not: (a) violate these Agreements, applicable law, or the intellectual property, publicity or personality rights of others; or (b) imply any affiliation, endorsement, approval or cooperation with you or your User Content by Syncify or any artist, band, label, entity or individual without express written consent from such individual or entity. You grant Syncify a non-exclusive, transferable, sub-licensable, royalty-free, worldwide licence to use, reproduce, make available to the public, publish, translate and distribute any User Content that you post on or otherwise provide through the Syncify Service. This license lasts until you terminate your Syncify account. Aside from the rights specifically granted herein, you retain ownership of all rights, including intellectual property rights, in the User Content that you post to the Syncify Service, except that, where applicable under Local Country law, you agree to waive your right to be identified as the author of any User Content on the Syncify Service and your right to object to derogatory treatment of such User Content.
Syncify does not monitor, review, or edit User Content, but reserves the right to remove or disable access to any User Content for any or no reason, including but not limited to, User Content that, in Syncify’s sole discretion, violates these Agreements. Syncify may take these actions without prior notification to you. Removal or disabling of access to User Content shall be at our sole discretion, and we do not promise to remove or disable access to any specific User Content.
Syncify is not responsible for User Content nor does it endorse any opinion contained in User Content. If you believe that any User Content infringes your intellectual property rights, please click here, or if you believe that any User Content does not comply with the User Guidelines (Section 8 below) or that your rights under applicable law have been otherwise infringed by any User Content, please contact us at hello@syncifynow.com  
</li>
		            	<li><strong>Consideration</strong><br>
In consideration for the rights granted to you under these Terms, you grant us the right (a) to allow the Syncify Service to use the processor, bandwidth and storage hardware on your Device in order to facilitate the operation of the Service, (b) to provide advertising and other information to you, and (c) to allow our business partners to do the same.
These Terms are not intended to grant rights to anyone except you and Syncify, and in no event shall these Terms create any third party beneficiary rights. Any failure by Syncify to enforce these Terms or any provision thereof shall not waive Syncify’s right to do so.
</li>
		            	<li><strong>User Guidelines</strong><br>
We’ve established a few ground rules for you to follow when using the Service, to make sure Syncify stays enjoyable for everyone. Please follow these rules and encourage other users to do the same.
Syncify respects intellectual property rights and expects you to do the same. This means, for example, that the following is not permitted: (a) Copying, reproducing, “ripping”, recording, or making available to the public any part of the Syncify Services or content delivered to you via the Syncify Services, or otherwise any making use of the Syncify Service which is not expressly permitted under these Terms; (b) using the Syncify service to import or copy any local files you do not have the legal right to import or copy in this way; (c) reverse-engineering, decompiling, disassembling, modification or creating derivative works based on the Syncify Services or any part thereof; (d) circumventing any technology used by Syncify, its licensors, or any third party to protect content accessible through the Service; (e) renting or leasing of any part of the Services; (f) circumventing of any territorial restrictions applied by Syncify; (g) artificially increasing play count or otherwise manipulating the Services by using a script or other automated process; (h) removing or altering any copyright, trademark or other intellectual property notices contained on or provided through the Syncify Service; (i) providing your password to any other person or using any other person’s username and password.
Please respect Syncify and other users of the Syncify Service. Don’t engage in any activity on the Service or upload User Content, including registering and/or using a username, which is or includes material that (a) is offensive, abusive, defamatory, pornographic or obscene; (b) is illegal, or intended to promote or commit an illegal act of any kind, including but not limited to, violations of intellectual property rights, privacy rights or proprietary rights of Syncify or a third party; (c) includes personal data of third parties or is intended to solicit such personal data, (d) includes malicious content such as malware, Trojan horses or viruses, or otherwise interferes with any user’s access to the Service; (e) is intended or does harass or bully other users; (f) impersonates or misrepresents your affiliation with another user, person or entity, or is otherwise fraudulent, false, deceptive, or misleading; (g) uses automated means to artificially promote content; (h) involves the transmission of unsolicited mass mailings or other forms of spam, junk mail, chain letter, or similar, including through the Syncify inbox; (i) involves commercial or sales activities, such as advertising, contests, sweepstakes, or pyramid schemes; (j) promotes commercial products or services (except as permitted under Section “Brand Accounts”); (k) interferes with the Syncify Service, tampers with or attempts to probe, scan, or test for vulnerabilities in the Service or Syncify computer systems or network, or breaches any of Syncify’s security or authentication measures, or (l) conflicts with the Agreements, as determined by Syncify. You agree that Syncify may also reclaim your username for any reason.
Please be thoughtful about what you make public on Syncify. The Syncify Service includes social and interactive features, including the ability to post User Content, share content, and make certain information about you public, as further described in your account settings. Remember that shared or publicly available information may be used and re-shared by other users on Syncify or across the web, so please use Syncify carefully and manage your account settings regularly. Syncify has no responsibility for your choices to make any actions or material public on the Service.
Your password protects your user account, and you are solely responsible for keeping your password confidential and secure. You understand that you are responsible for all use of your username and password on the Service. If your username or password is lost or stolen, or if you believe there has been unauthorized access to your account by third parties, please notify us immediately and change your password as soon as possible.
</li>
		            	<li><strong>Copyright infringement</strong><br>
Effective as of August 8th, 2015
Hello, and thank you for visiting Syncify’s copyright policy page. Syncify respects intellectual property rights and expects its users to do the same. If you are a copyright holder and you believe that any of the copyrighted material, which is directly available via the Syncify Service infringes your copyrighted work, please let us know.<br>
A notification of alleged copyright infringement must be addressed to Syncify’s copyright agent and include the following:
<ul>
	<li>A physical or electronic signature of the owner (or person authorized to act on behalf of the owner) of the copyright that is allegedly infringed;</li>
	<li>Specific identification of each copyrighted work claimed to have been infringed;</li>
	<li>A description of where the material believed to be infringed is located on Syncify Service or the Syncify Websites (please be as detailed as possible and provide a URL to help us locate the material you are reporting);</li>
	<li>Contact information for the complaining party, such as a complete name, address, telephone number, and email address;</li>
	<li>A statement that the complaining party has a good faith belief that use of the work(s) in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
	<li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. 
We should also let you know that Syncify has a policy to terminate in appropriate circumstances the accounts of subscribers who are repeat infringers.</li>
</ul>	
</li>
		            	<li><strong>Technology limitations and modifications</strong><br>
Syncify will make reasonable efforts to keep the Syncify Service operational. However, certain technical difficulties or maintenance may, from time to time, result in temporary interruptions. Syncify reserves the right, periodically and at any time, to modify or discontinue, temporarily or permanently, functions and features of the Syncify Service, with or without notice, all without liability to you for any interruption, modification, or discontinuation of the Syncify Service or any function or feature thereof. You understand and agree that Syncify has no obligation to maintain, support, upgrade, or update the Service, or to provide all or any specific content through the Service.
</li>
		            	<li><strong>Brand Accounts</strong><br>
If you establish a Syncify account on behalf of a company, organization, entity or brand (a “Brand Account”): (a) the terms “you” and “your”, as used throughout the Terms, apply to both you and the Brand (as defined below), as applicable; and (b) the following additional terms apply to your use of the Syncify Service for such purposes (the “Brand Account Terms”). To the extent of a conflict between these Brand Account Terms and the rest of the Terms, these Brand Account Terms shall apply, solely with respect to your Brand Account.
If you open a Brand Account, you represent and warrant that you are authorized to grant all permissions and licenses provided in these Terms and to bind the applicable company, organization, entity or brand (the “Brand”) to these Terms. Syncify has no obligation to promote the Brand Account profile or Brand Playlists (as defined below) and reserves the right to remove or disable access to a Brand’s User Content or profile, consistent with these Terms.
</li>
		            	<li><strong>Term and termination</strong><br>
These Terms will continue to apply to you until terminated by either you or Syncify. Syncify may terminate the Terms or suspend your access to the Syncify Service at any time, including in the event of your actual or suspected unauthorised use of the Syncify Service or non-compliance with the Terms. If you or Syncify terminate the Terms, or if Syncify suspends your access to the Syncify Service, you agree that Syncify shall have no liability or responsibility to you and Syncify will not refund any amounts that you have already paid, to the fullest extent permitted under applicable law. To learn how to terminate your Syncify account, please contact us through the Customer Service contact form.
</li>
		            	<li><strong>Warranty</strong><br>
We endeavor to provide the best service we can, but you understand and agree that THE SYNCIFY SERVICE IS PROVIDED “AS IS”, WITHOUT EXPRESS OR IMPLIED WARRANTY OR CONDITION OF ANY KIND. YOU USE THE SYNCIFY SERVICE AT YOUR OWN RISK. SYNCIFY MAKES NO REPRESENTATIONS AND DISCLAIMS ANY WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT.
In addition, Syncify makes no representation nor does it warrant, endorse, guarantee or assume responsibility for any Third Party Applications, Third Party Application content, User Content, or any other product or service advertised or offered by a third party on or through the Syncify Service or any hyperlinked website, or featured in any banner or other advertising. You understand and agree that Syncify is not responsible or liable for any transaction between you and third-party providers of Third Party Applications or products or services advertised on or through the Syncify Service. As with any purchase of a product or service through any medium or in any environment, you should use your judgment and exercise caution where appropriate. No advice or information whether oral or in writing obtained by you from Syncify shall create any warranty on behalf of Syncify in this regard. Some aspects of this section may not apply in some jurisdictions.
</li>
		            	<li><strong>Limitation</strong><br>
You agree that, to the extent permitted by applicable law, your sole and exclusive remedy for any problems or dissatisfaction with the Syncify Service, the Third Party Applications or the Third Party Application content is to uninstall any Syncify software and to stop using the Syncify Service, the Third Party Applications or the Third Party Application content.
TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL SYNCIFY, ITS OFFICERS, SHAREHOLDERS, EMPLOYEES, AGENTS, DIRECTORS, SUBSIDIARIES, AFFILIATES, SUCCESSORS, ASSIGNEES, SUPPLIERS OR LICENSORS BE LIABLE FOR (i) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE, EXEMPLARY OR CONSEQUENTIAL (INCLUDING LOSS OF USE, DATA, BUSINESS, OR PROFITS) DAMAGES, ARISING OUT OF THE USE OR INABILITY TO USE THE SYNCIFY SERVICE, THIRD PARTY APPLICATIONS OR THIRD PARTY APPLICATION CONTENT, REGARDLESS OF LEGAL THEORY, WITHOUT REGARD TO WHETHER SYNCIFY HAS BEEN WARNED OF THE POSSIBILITY OF THOSE DAMAGES, AND EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE; (ii) AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SYNCIFY SERVICE, THIRD PARTY APPLICATIONS OR THIRD PARTY APPLICATION CONTENT MORE THAN THE AMOUNTS PAID BY YOU TO SYNCIFY DURING THE PRIOR THREE MONTHS IN QUESTION.
Nothing in these Agreements removes or limits Syncify’s liability for fraud, fraudulent misrepresentation, death or personal injury caused by its negligence. Some aspects of this section may not apply in some jurisdictions.
</li>
		            	<li><strong>Entire agreement</strong><br>
Subject to this Section, these Agreements constitute all the terms and conditions agreed upon between you and Syncify and supersede any prior agreements in relation to the subject matter of these Agreements, whether written or oral. Any additional or different terms or conditions in relation to the subject matter of the Agreements in any written or oral communication from you to Syncify are void. You represent that you have not accepted the Agreements in reliance on any oral or written representations made by Syncify that are not contained in the Agreements.
Please note, however, that other aspects of your use of the Syncify Service may be governed by additional agreements. That could include, for example, access to the Syncify Community for customer support, access to the Syncify Service as a result of a gift card, or free or discounted Trials. You will agree to additional terms and conditions in those circumstances. Those terms and conditions shall govern only with regard to the aspect of the Service to which they apply, and are distinct from and supplemental to these Agreements, and do not supersede these Agreements. To the extent that there is any conflict between those agreements and these Agreements, these Agreements shall control, except as otherwise provided in these Terms.
</li>
		            	<li><strong>Severability</strong><br>
Should any provision of the Terms be held invalid or unenforceable for any reason or to any extent, such invalidity or enforceability shall not in any manner affect or render invalid or unenforceable the remaining provisions of the Terms, and the application of that provision shall be enforced to the extent permitted by law.
</li>
		            	<li><strong>Choice of law, mandatory arbitration and venue</strong><br>
Unless otherwise required by a mandatory law of any other jurisdiction, these Agreements shall be governed and construed in accordance with the laws of the Province of Ontario and the federal laws applicable therein without regard to its conflict of law provisions. Further, you and Syncify agree that the sole and exclusive venue for the resolution of any dispute, controversy or claim arising out of or in connection with this Agreement shall lie in the courts located within the province of Ontario, Canada.<br>
If you are a United States user, the following mandatory arbitration provisions also apply to you:
<ol>
	<li>You and Syncify agree that any dispute, claim or controversy arising out of or relating in any way to the Syncify Service or your use thereof, including our Agreements, shall be determined by mandatory binding arbitration. You agree that the U.S. Federal Arbitration Act governs the interpretation and enforcement of this provision, and that you and Syncify are each waiving the right to a trial by jury and the right to participate in a class or multi-party action. This arbitration provision shall survive termination of these Agreements and the termination of your Syncify account. The arbitration will be governed by the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes of the American Arbitration Association (the “AAA Rules”), as modified by these Agreements, and as administered by the AAA. You and Syncify agree that these Agreements involve interstate commerce and are subject to the Federal Arbitration Act.</li>
	<li>You and Syncify agree that (a) any claims seeking to enforce, protect, or determine the validity or ownership of any intellectual property rights, and (b) any claims related to allegations of theft, piracy or unauthorized use of the Syncify Service are NOT subject to mandatory arbitration. Instead, you and Syncify agree that these claims (including but not limited to claims for injunctive or equitable relief) shall be exclusively decided by courts of competent jurisdiction in San Francisco County, California or New York, New York, and that applicable California and/or Federal law shall govern, without regard to choice of law principles.</li>
	<li>YOU AND SYNCIFY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A CLASS MEMBER OR IN ANY REPRESENTATIVE CAPACITY OR PROCEEDING. Further, no arbitrator shall consolidate any other person’s claims with your claims, and may not otherwise preside over any form of a multi-party or class proceeding. If this specific provision is found to be unenforceable in any way, then the entirety of this arbitration section shall be null and void. The arbitrator may not award declaratory or injunctive relief.</li>
	<li>Any arbitration must be commenced by filing a demand for arbitration with the AAA within ONE (1) YEAR after the date the party asserting the claim first knows or reasonably should know of the act, omission or default giving rise to the claim; and there shall be no right to any remedy for any claim not asserted within that time period. If applicable law prohibits a one-year limitations period for asserting claims, any claim must be asserted within the shortest time period permitted by applicable law. Your arbitration fees and your share of arbitrator compensation will be limited to those fees set forth in the AAA's Consumer Rules with the remainder paid by Syncify. Any arbitration costs or fees deemed “excessive” will be paid by Syncify.</li>
</ol>

</li>
		            	<li><strong>Language</strong><br>
The parties hereto have agreed that this Agreement and any of its accessories, including notice, be written in the English language.

</li>
	            	</ol>
            	</p>
            </div>
          </div>
        </div>
      </section>
      <?php include'footer.php';?>